apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "user-service"
  annotations:
    github.com/project-slug: svetamint/user-service
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: edy2cpu3h1f5se
  links:
    - url: http://localhost:3003
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard  
spec:
  type: service
  lifecycle: experimental
  owner: team-b
  system: delivery-portal
  providesApis:
    - user-api
  consumesApis:
   - common-validation
