apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "user-service"
  annotations:
    github.com/project-slug: svetamint/user-service
    github.com/project-cicd: https://github.com/svetamint/user-service/actions
    backstage.io/techdocs-ref: url:https://github.com/svetamint/user-service
spec:
  type: service
  lifecycle: experimental
  owner: team-b
  system: delivery-portal
  # providesApis:
  #   - create-user
  #   - update-user
  #   - delete-user
  #   - find-all-users
  #   - find-user-by-id
  #   - find-user-by-email
