name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user-service repository
        uses: actions/checkout@v2

      - name: Checkout proto-common repository
        run: git clone https://github.com/kkorchyts/proto-common.git

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: List files for debugging
        run: ls -R

      - name: Build and install proto-common
        run: |
          cd proto-common
          mvn clean install

      - name: Build user-service
        run: |
          mvn clean package

      - name: Run tests for user-service
        run: |
          mvn test

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: junit-results
          path: target/surefire-reports/*.xml
